# Generated by Django 2.1.2 on 2018-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ap_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ap',
            },
        ),
    ]
